# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/Singularity',
                'doc_host': 'https://rrayanna.github.io',
                'git_url': 'https://github.com/rrayanna/Singularity',
                'lib_path': 'Singularity'},
  'syms': {'Singularity.core': {'Singularity.core.foo': ('core.html#foo', 'Singularity/core.py')}}}
